/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResourcesImport } from './routes/resources'
import { Route as MapsImport } from './routes/maps'
import { Route as DatabaseImport } from './routes/database'
import { Route as IndexImport } from './routes/index'
import { Route as MapTestIndexImport } from './routes/map-test/index'
import { Route as MapTestMaplibreImport } from './routes/map-test/maplibre'
import { Route as MapTestLeafletImport } from './routes/map-test/leaflet'

// Create/Update Routes

const ResourcesRoute = ResourcesImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRoute,
} as any)

const MapsRoute = MapsImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRoute,
} as any)

const DatabaseRoute = DatabaseImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MapTestIndexRoute = MapTestIndexImport.update({
  id: '/map-test/',
  path: '/map-test/',
  getParentRoute: () => rootRoute,
} as any)

const MapTestMaplibreRoute = MapTestMaplibreImport.update({
  id: '/map-test/maplibre',
  path: '/map-test/maplibre',
  getParentRoute: () => rootRoute,
} as any)

const MapTestLeafletRoute = MapTestLeafletImport.update({
  id: '/map-test/leaflet',
  path: '/map-test/leaflet',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseImport
      parentRoute: typeof rootRoute
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsImport
      parentRoute: typeof rootRoute
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesImport
      parentRoute: typeof rootRoute
    }
    '/map-test/leaflet': {
      id: '/map-test/leaflet'
      path: '/map-test/leaflet'
      fullPath: '/map-test/leaflet'
      preLoaderRoute: typeof MapTestLeafletImport
      parentRoute: typeof rootRoute
    }
    '/map-test/maplibre': {
      id: '/map-test/maplibre'
      path: '/map-test/maplibre'
      fullPath: '/map-test/maplibre'
      preLoaderRoute: typeof MapTestMaplibreImport
      parentRoute: typeof rootRoute
    }
    '/map-test/': {
      id: '/map-test/'
      path: '/map-test'
      fullPath: '/map-test'
      preLoaderRoute: typeof MapTestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/maps': typeof MapsRoute
  '/resources': typeof ResourcesRoute
  '/map-test/leaflet': typeof MapTestLeafletRoute
  '/map-test/maplibre': typeof MapTestMaplibreRoute
  '/map-test': typeof MapTestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/maps': typeof MapsRoute
  '/resources': typeof ResourcesRoute
  '/map-test/leaflet': typeof MapTestLeafletRoute
  '/map-test/maplibre': typeof MapTestMaplibreRoute
  '/map-test': typeof MapTestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/maps': typeof MapsRoute
  '/resources': typeof ResourcesRoute
  '/map-test/leaflet': typeof MapTestLeafletRoute
  '/map-test/maplibre': typeof MapTestMaplibreRoute
  '/map-test/': typeof MapTestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/database'
    | '/maps'
    | '/resources'
    | '/map-test/leaflet'
    | '/map-test/maplibre'
    | '/map-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/database'
    | '/maps'
    | '/resources'
    | '/map-test/leaflet'
    | '/map-test/maplibre'
    | '/map-test'
  id:
    | '__root__'
    | '/'
    | '/database'
    | '/maps'
    | '/resources'
    | '/map-test/leaflet'
    | '/map-test/maplibre'
    | '/map-test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseRoute: typeof DatabaseRoute
  MapsRoute: typeof MapsRoute
  ResourcesRoute: typeof ResourcesRoute
  MapTestLeafletRoute: typeof MapTestLeafletRoute
  MapTestMaplibreRoute: typeof MapTestMaplibreRoute
  MapTestIndexRoute: typeof MapTestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseRoute: DatabaseRoute,
  MapsRoute: MapsRoute,
  ResourcesRoute: ResourcesRoute,
  MapTestLeafletRoute: MapTestLeafletRoute,
  MapTestMaplibreRoute: MapTestMaplibreRoute,
  MapTestIndexRoute: MapTestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/database",
        "/maps",
        "/resources",
        "/map-test/leaflet",
        "/map-test/maplibre",
        "/map-test/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/database": {
      "filePath": "database.tsx"
    },
    "/maps": {
      "filePath": "maps.tsx"
    },
    "/resources": {
      "filePath": "resources.tsx"
    },
    "/map-test/leaflet": {
      "filePath": "map-test/leaflet.tsx"
    },
    "/map-test/maplibre": {
      "filePath": "map-test/maplibre.tsx"
    },
    "/map-test/": {
      "filePath": "map-test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
